# Generated by Django 2.2.7 on 2020-02-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosyrienapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugees2011',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2012',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2013',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2014',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2015',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2016',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2017',
            old_name='coord',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='refugees2018',
            old_name='coord',
            new_name='geom',
        ),
    ]
