# Generated by Django 2.2.7 on 2020-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosyrienapp', '0002_auto_20200227_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugees2011',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2012',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2013',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2014',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2015',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2016',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2017',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugees2018',
            name='haltung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
